module.exports = {
  GET_DATA_SUCCESS: "Dữ liệu đã được lấy thành công!",
  MESSAGE_SUCCESS: "Thêm dữ liệu thành công!",
  MESSAGE_FAILED: "Thêm dữ liệu thất bại!",
  DATA_NOT_FOUND: "Không tìm thấy dữ liệu!",
  DELETE_SUCCESS: "Xóa dữ liệu thành công!",
  DELETE_FAILED: "Xóa dữ liệu thất bại!",
  UPDATE_SUCCESS: "Cập nhật dữ liệu thành công!",
  UPDATE_FAILED: "Cập nhật liệu thất bại!",
  COMMENT_SUCCESS: "Bạn đã bình luận thành công!",
  COMMENT_FAILED: "Bạn bình luận thất lại!",
  FOLLOW_SUCCESS: "Theo dõi thành công!",
  FOLLOW_FAILED: "Theo dõi thất bại!",
  UNFOLLOW_SUCCESS: "Bỏ theo dõi thành công!",
  UNFOLLOW_FAILED: "Bỏ theo dõi thất bại!",
  VERIFIED_SUCCESS: "Xác thực tài khoản thành công!",
  BLOCKED_SUCCESS: "Chặn tài khoản thành công!",
  UNBLOCKED_SUCCESS: "Bỏ chặn tài khoản thành công!",
};
